bootstrap.servers = hadoop202:9092
key.deserializer = org.apache.kafka.common.serialization.StringDeserializer
value.deserializer = org.apache.kafka.common.serialization.StringDeserializer
key.serializer = org.apache.kafka.common.serialization.StringSerializer
value.serializer = org.apache.kafka.common.serialization.StringSerializer
group.id = g002
enable.auto.commit = true
auto.commit.interval.ms = 5000
auto.offset.reset = earliest